-- Create all sequences for auto-incrementing IDs
CREATE SEQUENCE seq_manufacturers START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_medicines START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_batches START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_recalls START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_users START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_alerts START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_audit_logs START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_holidays START WITH 1 INCREMENT BY 1;

-- Verify sequences
SELECT sequence_name FROM user_sequences;